name: Release

on:
  push:
    tags:
      - "v*"

env:
  TARGET_NAME: "open-browser-time"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ '22.x' }}
          cache: npm

      - name: Install npm dependencies
        run: npm install

      - name: Build the extension
        run: |
          npm run build

      - name: Check version match
        run: |
          VERSION=$(jq -r .version public/manifest.json)
          TAG_VERSION=${GITHUB_REF:10}
          if [ "$VERSION" != "${TAG_VERSION#v}" ]; then
            echo "Version in public/manifest.json ($VERSION) does not match release tag version (${TAG_VERSION#v})"
            exit 1
          fi

      - name: Package
        run: |
          mkdir -p ./release
          CHROME_EXT_NAME="${{ env.TARGET_NAME }}-chrome"
          mv dist "./release/$CHROME_EXT_NAME"
          zip -r "./release/$CHROME_EXT_NAME.zip" "./release/$CHROME_EXT_NAME"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./release/*.zip
