name: Release

on:
  push:
    tags:
      - "v*"

env:
  TARGET_NAME: "open-browser-time"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ '22.x' }}
          cache: npm

      - name: Install npm dependencies
        run: npm install

      - name: Build the extension
        run: |
          npm run build

      - name: Check version match
        run: |
          VERSION=$(jq -r .version public/manifest.json)
          if [ "$VERSION" != "${GITHUB_REF:10}" ]; then
            echo "Version in public/manifest.json ($VERSION) does not match release tag version (${GITHUB_REF:10})"
            exit 1
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{env.TARGET_NAME}}
          files: |
            dist
